### ISSUE TITLE
Scales create NamedBlobImage with wrong contentType field

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.namedfile#38]
`NamedBlobImage` `contentType` field [should be **string** not **unicode**](https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/usage.rst).

But when the image is scaled, [it becomes **unicode**](https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/scaling.py#L236-L241), what creates validation issues in image fields [1](https://community.plone.org/t/migration-collective-jsonify-news-item-images-lead-image-wrong-contained-type/1544), [2](https://github.com/collective/collective.cover/issues/637).

This bug was introduced in [this refactoring](https://github.com/plone/plone.namedfile/commit/33df023d09c3d18df14f7f93feeca2ba5bf19c88#diff-03f29bbadcdf640341c9061de5a07dccR299).

**Comment by hvelarde** [comment]
I can confirm this issue and I can also confirm fixing it is not that easy as getting rid of the `u''` as all scales in the portal created with the wrong content type will have wrong information.

we need to write an upgrade step or to find out a good place for data casting.

@plone/framework-team ideas?

**Comment by rodfersou** [comment]
maybe we can add a cast before raise the validation exception first.

**Comment by rodfersou** [comment]
A little bit more information about the original exception:

```python
/home/rodfersou/.anyenv/envs/pyenv/versions/2.7.12/envs/collective.cover/lib/python2.7/site-packages/IPython/core/debugger.py:238: DeprecationWarning: The `color_scheme` argument is deprecated since version 5.1
  DeprecationWarning)
> /home/rodfersou/.projects/cache/eggs/zope.schema-4.2.2-py2.7.egg/zope/schema/_bootstrapfields.py(210)_validate()
    208         if self._type is not None and not isinstance(value, self._type):
    209             import debug
--> 210             raise WrongType(value, self._type, self.__name__)
    211 
    212         if not self.constraint(value):

ipdb> value
u'image/jpeg'
ipdb> self._type
<type 'str'>
ipdb> self
<zope.schema._field.BytesLine object at 0x7f0b568b7c50>
ipdb> self.__name__
'contentType'
```

**Comment by gforcada** [comment]
a try..except with a note could be a good idea, with a comment pointing to this issue for example.

**Comment by rodfersou** [comment]
@gforcada where would be the right place for this try..except?

**Comment by gforcada** [comment]
@rodfersou you were pointing to a single place where this could be wrapped in a try..except already some comments above: https://github.com/plone/plone.namedfile/issues/38#issuecomment-268885793

**Comment by rodfersou** [comment]
@gforcada I'm not sure if the place I pointed is the right one, since the exception is too generic for many cases.

maybe add a IF statement to don't raise the exception in one specific condition would work out.

**Comment by hvelarde** [comment]
@thet comments, please!

**Comment by thet** [comment]
@hvelarde @rodfersou an upgrade step to fix the wrong contentType values + a plone.namedfile fix to not turn the contentType to unicode would be it, IMO.
@hvelarde anything else you need me to comment on?

**Comment by thet** [comment]
A try..except in zope.schema with a cast on except is not an option, if understood the discussion above correctly.

**Comment by rodfersou** [comment]
@thet can you guide me on how this upgrade step would be? are there any way to search for every configlet with image widget where this exception happen?

**Comment by hvelarde** [comment]
@rodfersou keep it simple: search for images and scales only; my only concern is about memory consumption of the upgrade step.

**Comment by thet** [comment]
+1 

I can help out next week. I'm currently on my way back to Austria.


sent from mobile






On Tue, Jan 3, 2017 at 12:03 PM -0600, "Héctor Velarde" <notifications@github.com> wrote:












@rodfersou keep it simple: search for images and scales only; my only concern is about memory consumption of the upgrade step.

**Comment by thet** [comment]
Should be fixed via:
https://github.com/plone/plone.namedfile/pull/41
and
https://github.com/plone/plone.namedfile/pull/45
