### ISSUE TITLE
Svg image not displaying

### ISSUE THREAD

**Issue by gp54321** [plone/plone.namedfile#63]
steps:
add a new image. Browse to a svg image file. click save.
expected;
the image is displayed
result:
image is not displayed, only a link with the file size.

Plone version: 5.1.2 soft released, ie plone.namedfile-4.2.4

remarks:
there are 2 problems:
- when an exception is thrown by PIL library, file has begun to be read so the scale is saved with the beginning of file missing
- modern browsers expect a mime type of svg+xml
Suggested change:
```
--- scaling.py.ori	2018-04-09 16:41:02.121472000 +0000
+++ scaling.py	2018-04-11 13:33:23.624061095 +0000
@@ -245,7 +245,8 @@
             raise
         except IOError:
             if getattr(orig_value, 'contentType', '') == 'image/svg+xml':
-                result = orig_data.read(), 'SVG', (width, height)
+                orig_data.seek(0)
+                result = orig_data.read(), 'SVG+XML', (width, height)
             else:
                 logger.exception(
                     'Could not scale "{0!r}" of {1!r}'.format(
```
Full screen display does not work of course, but it would need to pull lxml in the picture so it's more complicated.

**Comment by jensens** [comment]
closed with #83
