### ISSUE TITLE
Get rid of the ImageScale unregistered view

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.namedfile#79]
This view `ImageScale` is not registered in any zcml:
https://github.com/plone/plone.namedfile/blob/5cb83ff5284a9cd3576458c47ff259a2034d3fad/plone/namedfile/scaling.py#L39

and it is just used by the view `ImageScaling` view (registered in a zcml for the name images):

https://github.com/plone/plone.namedfile/blob/5cb83ff5284a9cd3576458c47ff259a2034d3fad/plone/namedfile/scaling.py#L281

I bet it should be possible to come up with a simpler solution.
Now debugging/customizing is pretty hard

**Comment by petschki** [comment]
since merged is this fixed?
