### ISSUE TITLE
What about a new release?

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.namedfile#95]
In master we have support with the range support feature #86
It is really cool and I am already using it in production since a while.
It might be good to have a release, given that 5.2.2 is expected soon and for some reason (maybe https://github.com/plone/mr.roboto/issues/79) the package is not in the checkouts:
https://github.com/plone/buildout.coredev/blob/5.2/checkouts.cfg

**Comment by tisto** [comment]
Released: https://pypi.org/project/plone.namedfile/5.4.0/

**Comment by tisto** [comment]
@mauritsvanrees I guess it is up to you to decide if that goes into 5.2 or 6.0 only.

**Comment by ale-rt** [comment]
If that might help I am using this in production with Plone 5.2.1 since a while with no issue.
I think @pbauer and @mamico can also confirm positive experiences with Plone 5.2.

**Comment by mauritsvanrees** [comment]
Thanks.
`mr.roboto` is definitely the issue here. To combat this problem, I have regularly run `bin/manage report --interactive` in coredev to keep `checkouts.cfg` updated. But apparently this fallback is not working either... I see some suspicious code in `plone.releaser`, but the suspicious part is five years old. I am investigating now.

**Comment by mauritsvanrees** [comment]
I have committed a fix to `plone.releaser` to fix it `manage report` command.

BTW @tisto: you made the release, and it ended up fine on PyPI, but the tag and the postrelease commit did not end up on GitHub. Only the release commit 9b2c3de90390f54ea8e06a469aefc2042e0ca332 made it. The same thing happened a few days ago for `plone.schemaeditor`.  I created the tag and postrelease commit for both and pushed it, so all is fine now.

But there is still something fishy in your setup. Probably again `towncrier` related. I still have half a mind to replace `towncrier` and `zestreleaser.towncrier` with something simpler. `towncrier` and `zest.releaser` partially want to do the same thing, and 99 out of 100 times the combination works fine for me, but for you and maybe others things fall through the cracks.

**Comment by mauritsvanrees** [comment]
Fine to include the new release in the next 5.2.2 release.
And let's include the related https://github.com/plone/plone.app.caching/pull/58 (merged now) and https://github.com/plone/plone.formwidget.namedfile/pull/44 (Jenkins restarted now) as well.
