### ISSUE TITLE
TypeError after update from Plone 5.1.5 to 5.2.2

### ISSUE THREAD

**Issue by krissik** [plone/plone.namedfile#96]
After I have updated from Plone 5.1.5 to 5.2.2 an so from plone.namedfile-4.2.6 to plone.namedfile-5.4.0
I get a lot of `TypeErrors`

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 359, in publish_module
  Module ZPublisher.WSGIPublisher, line 250, in publish
  Module ZPublisher.BaseRequest, line 518, in traverse
  Module ZPublisher.BaseRequest, line 341, in traverseName
  Module plone.namedfile.scaling, line 307, in publishTraverse
  Module plone.namedfile.scaling, line 450, in scale
  Module plone.scale.storage, line 182, in scale
  Module plone.scale.storage, line 127, in _modified_since
  Module plone.scale.storage, line 143, in modified_time
TypeError: modified() takes exactly 1 argument (2 given)
```

and images are not shown anymore.

If I locally change https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/scaling.py#L439 to
```python
storage = AnnotationStorage(self.context, self.modified)
```
images are working again. This reverts one line of this commit
https://github.com/plone/plone.namedfile/commit/c1bed2fea3eb4290145ff772a676eba0be841e72#diff-03f29bbadcdf640341c9061de5a07dccL428

If I start with a new created database everything works as expected without this change.

I am not sure if this a problem with my database or a general problem. Did I miss to update another package? Maybe someone can help?

**Comment by mauritsvanrees** [comment]
The code looks fine. 
Note that the old `modified` function always returned the modified date of the context. The new function, when called with a fieldname as extra argument, as the `partials` call does, returns the modified date of the field.

Maybe the [`modified` method](https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/scaling.py#L399) is overridden somewhere, and the override does not accept the extra argument? I don't find such an override in core Plone though.

Maybe you have an add-on that does this? Maybe you could go in with a `pdb.set_trace()` and see what `self.modified` points to when it goes wrong.
Still, strange that it goes fine with a new database.
I wonder if the `AnnotationStorage` call somehow returns a persistent object, with an older 5.1 version of `modified` stored on it. But that sounds really weird. Also, I don't think you can persistently store a method.

Possibly something to try: in the migrated database, does it work fine when you create a new Image, or a NewsItem with image field?

**Comment by krissik** [comment]
Thank you very much!
There is indeed an overwrite of `modified`
